// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'navigation-content': string;
  'navigation-content__item': string;
  'navigation-content__item--logout': string;
}
export const cssExports: CssExports;
export default cssExports;
