// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'page': string;
  'page--active': string;
  'page__overlay': string;
  'slider': string;
  'slider-container': string;
  'slider__close-button': string;
  'slider__indicator': string;
  'slider__indicator-container': string;
}
export const cssExports: CssExports;
export default cssExports;
