// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'text-input': string;
  'text-input__error': string;
  'text-input__errors': string;
  'text-input__inner': string;
  'text-input__label': string;
  'text-input__max-length': string;
  'text-input__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
