// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons__button': string;
  'buttons__button--cancel': string;
  'buttons__wrapper': string;
  'manage-images__back': string;
  'manage-images__images-wrapper': string;
  'manage-images__page': string;
  'manage-images__section-title': string;
  'manage-images__stories-wrapper': string;
  'manage-images__title': string;
}
export const cssExports: CssExports;
export default cssExports;
