// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'verify-email__page': string;
  'verify-email__title': string;
}
export const cssExports: CssExports;
export default cssExports;
