// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-buttons': string;
  'action-buttons__icon-button': string;
  'action-buttons__icon-button--critical': string;
  'action-buttons__icon-button--disabled': string;
  'back-button': string;
  'back-button__title': string;
  'icon': string;
  'info__status--complete': string;
  'info__status--transcoding': string;
  'info__title': string;
  'info__title--transcoding': string;
  'stories': string;
  'stories--center': string;
  'stories-page': string;
  'stories__date': string;
  'stories__info': string;
  'story-preview__close-button': string;
  'story-preview__container': string;
  'upload-button': string;
  'videos__page': string;
}
export const cssExports: CssExports;
export default cssExports;
