// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image-input': string;
  'image-input__button': string;
  'image-input__error': string;
  'image-input__errors': string;
  'image-input__inner': string;
  'image-input__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
