// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-row': string;
  'button-row-container': string;
  'contact': string;
  'description': string;
  'details': string;
  'details-container': string;
  'feature': string;
  'features': string;
  'hidden-button': string;
  'information-bar': string;
  'left-side': string;
  'profile-image': string;
  'profile-image-container': string;
  'profile-page': string;
  'right-side': string;
  'shop-title': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
