// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'arrow-container': string;
  'bar': string;
  'brand': string;
  'button': string;
  'button-row': string;
  'button-row-container': string;
  'contact': string;
  'contacts': string;
  'date': string;
  'description': string;
  'details': string;
  'details-container': string;
  'feature': string;
  'feature-container': string;
  'feature-info': string;
  'features': string;
  'icon': string;
  'image': string;
  'information-bar': string;
  'leaflet-control-zoom': string;
  'left-side': string;
  'location': string;
  'location-container': string;
  'normal': string;
  'picture': string;
  'profile-image': string;
  'profile-image-container': string;
  'profile-page': string;
  'right-side': string;
  'row': string;
  'shop-title': string;
  'stories': string;
  'story': string;
  'story-container': string;
  'title': string;
  'updated': string;
}
export const cssExports: CssExports;
export default cssExports;
