// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-row': string;
  'description': string;
  'details': string;
  'feature': string;
  'features': string;
  'hidden-button': string;
  'profile-image': string;
  'profile-image-container': string;
  'profile-page': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
