// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-button': string;
  'action-buttons': string;
  'back-icon': string;
  'center': string;
  'date': string;
  'icon': string;
  'info': string;
  'nav-bar': string;
  'stories': string;
  'stories-page': string;
  'stories-page-container': string;
  'table': string;
  'upload-button': string;
}
export const cssExports: CssExports;
export default cssExports;
