// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'no-businesses-found': string;
  'no-businesses-found__link': string;
  'no-businesses-found__text': string;
}
export const cssExports: CssExports;
export default cssExports;
