// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'businesses-carousel': string;
  'businesses-carousel__swiper': string;
  'last-page': string;
  'last-page__button': string;
  'last-page__text': string;
}
export const cssExports: CssExports;
export default cssExports;
