// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amplifier': string;
  'input__error': string;
  'input__error-message': string;
  'input__error-messages': string;
  'input__errors': string;
  'input__field': string;
  'input__field--active': string;
  'input__inner': string;
  'input__inner--active': string;
  'input__label': string;
  'input__label--active': string;
  'input__login--text_amplifier': string;
  'input__max-length': string;
  'input__wrapper': string;
  'input__wrapper--active': string;
  'link': string;
  'link--small': string;
  'page': string;
  'page__subtitle': string;
  'page__title': string;
  'selection__checkbox': string;
  'selection__checkbox--selected': string;
  'selection__error': string;
  'selection__error-message': string;
  'selection__error-messages': string;
  'selection__errors': string;
  'selection__label': string;
  'selection__label--active': string;
  'selection__markup': string;
  'selection__wrapper': string;
  'submit': string;
  'text': string;
  'text--large': string;
  'text--primary': string;
  'text--small': string;
}
export const cssExports: CssExports;
export default cssExports;
