// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'landing-page': string;
  'logo': string;
  'logo-container': string;
  'navigation': string;
  'navigation__business': string;
  'navigation__business-link': string;
  'navigation__other': string;
  'navigation__other-link': string;
  'overlay-content': string;
  'overlay-content__link': string;
  'overlay-content__text1': string;
  'overlay-content__text2': string;
  'overlay-content__text3': string;
  'welcome': string;
  'welcome__desc': string;
  'welcome__title': string;
  'zip-container': string;
  'zip-container__field': string;
}
export const cssExports: CssExports;
export default cssExports;
