// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'business': string;
  'business__link': string;
  'button-container': string;
  'caption': string;
  'close-button': string;
  'desc': string;
  'icon': string;
  'landing-page': string;
  'link': string;
  'links': string;
  'location-button': string;
  'logo': string;
  'logo-container': string;
  'other': string;
  'other-text': string;
  'other__link': string;
  'overlay': string;
  'overlay-content': string;
  'search-icon': string;
  'text': string;
  'text-input': string;
  'text1': string;
  'text2': string;
  'text3': string;
  'title': string;
  'welcome': string;
  'zip-container': string;
  'zip-field': string;
}
export const cssExports: CssExports;
export default cssExports;
