// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'datenschutz': string;
  'datenschutz__section': string;
  'datenschutz__subsection': string;
  'datenschutz__title': string;
}
export const cssExports: CssExports;
export default cssExports;
