// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'overlay': string;
  'overlay--delete': string;
  'overlay--new': string;
  'thumbnail': string;
  'thumbnail__button': string;
  'thumbnail__button--delete': string;
  'thumbnail__buttons': string;
  'thumbnail__buttons--cover': string;
  'thumbnail__icon': string;
  'thumbnail__title': string;
  'thumbnail__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
