// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button__icon': string;
  'button__icon--disabled': string;
  'input': string;
  'input--centered': string;
  'input--disabled': string;
  'input--with-button': string;
  'input-container': string;
  'label': string;
  'label--centered': string;
  'label--with-button': string;
  'wvh-text-field': string;
}
export const cssExports: CssExports;
export default cssExports;
