// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'nutzungsbedingungen': string;
  'nutzungsbedingungen__section': string;
  'nutzungsbedingungen__title': string;
}
export const cssExports: CssExports;
export default cssExports;
