// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form-hints__bottom': string;
  'form-hints__title': string;
  'form-hints__top': string;
  'form-hints__wrapper': string;
  'manage-images__form': string;
  'manage-images__form-buttons': string;
  'manage-images__form-preview': string;
  'manage-images__upload-image-button': string;
}
export const cssExports: CssExports;
export default cssExports;
