// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amplifier': string;
  'input--text': string;
  'input__error': string;
  'input__error-message': string;
  'input__error-messages': string;
  'input__errors': string;
  'input__inner': string;
  'input__label': string;
  'input__wrapper': string;
  'link': string;
  'link--small': string;
  'page': string;
  'page__subtitle': string;
  'page__title': string;
  'submit': string;
  'text': string;
  'text--large': string;
  'text--primary': string;
  'text--small': string;
  'text-input': string;
  'text-input__error': string;
  'text-input__errors': string;
  'text-input__inner': string;
  'text-input__label': string;
  'text-input__max-length': string;
  'text-input__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
