// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'verification-toast__send-again': string;
}
export const cssExports: CssExports;
export default cssExports;
