// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'manage-profile__back': string;
  'manage-profile__form-wrapper': string;
  'manage-profile__page': string;
  'manage-profile__page__title': string;
}
export const cssExports: CssExports;
export default cssExports;
