// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'edit-image-form': string;
  'edit-image-form__buttons': string;
  'edit-image-form__delete': string;
  'edit-image-form__thumbnail': string;
  'edit-image-form__title': string;
}
export const cssExports: CssExports;
export default cssExports;
