// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logout-button': string;
  'navigation': string;
  'navigation-button': string;
  'navigation-button-container': string;
  'navigation-page': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
