// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logout__button': string;
  'logout__logo': string;
  'logout__page': string;
  'logout__title': string;
}
export const cssExports: CssExports;
export default cssExports;
