// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'close-button': string;
  'close-icon': string;
  'headline': string;
  'hidden': string;
  'icon': string;
  'overlay': string;
  'overlay-content': string;
  'preview': string;
  'story-page': string;
  'story-page-container': string;
  'visible': string;
}
export const cssExports: CssExports;
export default cssExports;
