// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'controls': string;
  'explore-page': string;
  'explorer': string;
  'header': string;
  'horizontal-swiper': string;
  'icon': string;
  'left-side': string;
  'logo': string;
  'name': string;
  'profile': string;
  'right-side': string;
  'short-desc': string;
  'story': string;
  'story-container': string;
  'vertical-swiper': string;
}
export const cssExports: CssExports;
export default cssExports;
