// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'explore-controls': string;
  'explore-controls__left-arrow': string;
  'explore-controls__middle-arrow': string;
  'explore-controls__right-arrow': string;
  'explore-controls__text': string;
  'explore-page': string;
  'explore-page__background': string;
  'explorer': string;
  'fadeInExploreControls': string;
  'horizontal-swiper': string;
  'icon': string;
  'last-page': string;
  'last-page__button': string;
  'last-page__text': string;
  'profile': string;
  'profile__placeholder': string;
  'settings': string;
  'settings-navigation': string;
  'settings-navigation__item': string;
  'settings-navigation__link': string;
  'top-controls': string;
  'vertical-swiper': string;
}
export const cssExports: CssExports;
export default cssExports;
