// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header-left-side': string;
  'header-left-side__logo': string;
  'header-right-side': string;
  'story': string;
  'story-container': string;
  'story-container__video-play-button': string;
  'story-video-controls': string;
  'story__background': string;
  'video-play-button-container': string;
  'video-play-button-container__button': string;
}
export const cssExports: CssExports;
export default cssExports;
