// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amplifier': string;
  'input--text': string;
  'input__error-message': string;
  'input__error-messages': string;
  'input__wrapper': string;
  'link': string;
  'link--small': string;
  'login__back': string;
  'login__button': string;
  'login__new-user': string;
  'login__page': string;
  'login__title': string;
  'page': string;
  'page__subtitle': string;
  'page__title': string;
  'submit': string;
  'text': string;
  'text--large': string;
  'text--primary': string;
  'text--small': string;
}
export const cssExports: CssExports;
export default cssExports;
