// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'wvh-app': string;
  'wvh-app-container': string;
}
export const cssExports: CssExports;
export default cssExports;
