// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input-container': string;
  'input-container--active': string;
  'input-container__button': string;
  'input-container__button--active': string;
  'input-container__button--disabled': string;
  'input-container__button-icon': string;
  'input-container__button-icon--active': string;
  'input-container__button-icon--disabled': string;
  'input-container__button-icon--inactive--disabled': string;
  'input-container__input-field': string;
  'input-container__input-field--active': string;
  'input-container__input-field--disabled': string;
  'text-input': string;
  'text-input--with-button': string;
}
export const cssExports: CssExports;
export default cssExports;
