// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input__button': string;
  'input__button--active': string;
  'input__button-icon': string;
  'input__button-icon--disabled': string;
  'input__input-field': string;
  'text-input': string;
  'text-input--with-button': string;
  'text-input__label': string;
}
export const cssExports: CssExports;
export default cssExports;
