// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amplifier': string;
  'footer': string;
  'input--text': string;
  'input__wrapper': string;
  'link--small': string;
  'page': string;
  'page__subtitle': string;
  'page__title': string;
  'submit': string;
  'text': string;
  'text--large': string;
  'text--primary': string;
  'text--small': string;
}
export const cssExports: CssExports;
export default cssExports;
