// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close-button': string;
  'error': string;
  'icon': string;
  'loading-error': string;
  'loading-error-container': string;
  'message': string;
  'retry': string;
}
export const cssExports: CssExports;
export default cssExports;
