// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'register-complete__button': string;
  'register-complete__page': string;
  'register-complete__title': string;
  'text--primary': string;
}
export const cssExports: CssExports;
export default cssExports;
