// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'manage-profile__form': string;
  'manage-profile__section-title': string;
  'manage-profile__submit': string;
}
export const cssExports: CssExports;
export default cssExports;
