// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'request-new-password__form': string;
}
export const cssExports: CssExports;
export default cssExports;
