// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'textarea': string;
  'textarea__error': string;
  'textarea__errors': string;
  'textarea__label': string;
  'textarea__max-length': string;
  'textarea__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
