// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close-button': string;
  'close-button__icon': string;
  'page': string;
  'page--active': string;
}
export const cssExports: CssExports;
export default cssExports;
