// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'story': string;
  'story__container--video': string;
  'story__message': string;
  'story__video': string;
  'video-play-button-container': string;
  'video-play-button-container__button': string;
}
export const cssExports: CssExports;
export default cssExports;
