// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back-button': string;
  'back-button__title': string;
  'form-hints__title': string;
  'form-hints__wrapper': string;
  'upload-video__back': string;
  'upload-video__back-icon': string;
  'upload-video__form': string;
  'upload-video__form-buttons': string;
  'upload-video__form-preview': string;
  'upload-video__page': string;
  'upload-video__preview': string;
  'upload-video__progress': string;
  'upload-video__title': string;
  'upload-video__upload-video-button': string;
}
export const cssExports: CssExports;
export default cssExports;
