// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form-hints__hint': string;
  'form-hints__title': string;
  'form-hints__wrapper': string;
  'new-image-form': string;
  'new-image-form__buttons': string;
  'new-image-form__preview': string;
  'new-image-form__title': string;
  'new-image-form__upload-image-button': string;
}
export const cssExports: CssExports;
export default cssExports;
