// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'landing': string;
  'landing__actions': string;
  'landing__actions-separator': string;
  'landing__background': string;
  'landing__title': string;
  'landing__title--larger': string;
  'navigation': string;
  'navigation__business-link': string;
  'navigation__legal-links': string;
  'navigation__other-link': string;
  'zip-container': string;
}
export const cssExports: CssExports;
export default cssExports;
