// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'reset-password__back': string;
  'reset-password__page': string;
  'reset-password__title': string;
}
export const cssExports: CssExports;
export default cssExports;
