// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'vertical-swiper': string;
  'vertical-swiper--transition': string;
}
export const cssExports: CssExports;
export default cssExports;
