// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checkbox--active': string;
  'input': string;
  'input__label--checkbox': string;
}
export const cssExports: CssExports;
export default cssExports;
