// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'leaflet-marker-icon': string;
  'map': string;
  'map-page': string;
}
export const cssExports: CssExports;
export default cssExports;
