// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-bar': string;
  'close-icon': string;
  'filter-icon': string;
  'leaflet-marker-icon': string;
  'logo': string;
  'logo-container': string;
  'map': string;
  'map-page': string;
  'title': string;
  'wvh-header': string;
}
export const cssExports: CssExports;
export default cssExports;
