// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'image-forms': string;
  'image-forms--active': string;
  'image-forms__button': string;
  'image-forms__container': string;
  'image-forms__icon': string;
  'image-forms__icon--close': string;
  'image-forms__overlay': string;
}
export const cssExports: CssExports;
export default cssExports;
