// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'explore-controls': string;
  'explore-controls--hidden': string;
  'explore-controls__arrow': string;
  'explore-controls__arrow--left': string;
  'explore-controls__arrow--middle': string;
  'explore-controls__arrow--right': string;
  'explore-controls__text': string;
  'fadeInExploreControls': string;
  'pulseExploreControls': string;
}
export const cssExports: CssExports;
export default cssExports;
