// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'explore-page': string;
  'header': string;
  'horizontal-swiper': string;
  'left-side': string;
  'logo': string;
  'name': string;
  'right-side': string;
  'short-desc': string;
  'vertical-swiper': string;
}
export const cssExports: CssExports;
export default cssExports;
