// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'impressum': string;
  'impressum__section': string;
  'impressum__title': string;
}
export const cssExports: CssExports;
export default cssExports;
