// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'register__back': string;
  'register__button': string;
  'register__existing-user': string;
  'register__page': string;
  'register__title': string;
  'text--primary': string;
}
export const cssExports: CssExports;
export default cssExports;
