// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'primary': string;
  'wvh-button': string;
  'wvh-button-container': string;
}
export const cssExports: CssExports;
export default cssExports;
