// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'wvh-button__container': string;
  'wvh-button__container--large': string;
  'wvh-button__container--primary': string;
}
export const cssExports: CssExports;
export default cssExports;
