// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'landing__button': string;
  'landing__buttons': string;
  'landing__page': string;
  'landing__subtitle': string;
  'landing__text': string;
  'landing__title': string;
  'landing__to-user-frontend': string;
}
export const cssExports: CssExports;
export default cssExports;
