// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amplifier': string;
  'input--text': string;
  'input__error-message': string;
  'input__error-messages': string;
  'input__wrapper': string;
  'landing__button': string;
  'landing__buttons': string;
  'landing__page': string;
  'landing__subtitle': string;
  'landing__text': string;
  'landing__title': string;
  'landing__to-user-frontend': string;
  'link': string;
  'link--small': string;
  'page': string;
  'page__subtitle': string;
  'page__title': string;
  'submit': string;
  'text': string;
  'text--large': string;
  'text--primary': string;
  'text--small': string;
}
export const cssExports: CssExports;
export default cssExports;
