// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'buttons': string;
  'continue-icon': string;
  'desc': string;
  'landing-page': string;
  'logo': string;
  'logo-container': string;
  'text-input': string;
  'title': string;
  'welcome': string;
}
export const cssExports: CssExports;
export default cssExports;
