// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dashboard__button': string;
  'dashboard__logo': string;
  'dashboard__page': string;
}
export const cssExports: CssExports;
export default cssExports;
