// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'login__button': string;
  'login__new-user': string;
  'login__page': string;
  'login__title': string;
  'text--primary': string;
}
export const cssExports: CssExports;
export default cssExports;
