// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'textarea': string;
  'textarea__field': string;
  'textarea__inner': string;
}
export const cssExports: CssExports;
export default cssExports;
