// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editor': string;
  'headline': string;
  'information-page': string;
  'information-page-container': string;
  'inputs': string;
  'label': string;
  'section': string;
  'selection': string;
  'switch': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
