// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'reset-password-success__page': string;
  'reset-password-success__title': string;
}
export const cssExports: CssExports;
export default cssExports;
