// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close-button': string;
  'icon': string;
  'legal': string;
  'legal__paragraph': string;
  'legal__section': string;
  'legal__subsection': string;
  'legal__title': string;
}
export const cssExports: CssExports;
export default cssExports;
