// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back-icon': string;
  'check-icon': string;
  'nav-bar': string;
  'save-icon': string;
}
export const cssExports: CssExports;
export default cssExports;
