// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button-container': string;
  'caption': string;
  'landing-page': string;
  'logo': string;
  'logo-container': string;
  'other-text': string;
}
export const cssExports: CssExports;
export default cssExports;
