// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-container': string;
  'caption': string;
  'desc': string;
  'icon': string;
  'landing-page': string;
  'link': string;
  'location-button': string;
  'logo': string;
  'logo-container': string;
  'other-text': string;
  'overlay': string;
  'search-icon': string;
  'text': string;
  'text-input': string;
  'text1': string;
  'text2': string;
  'text3': string;
  'title': string;
  'welcome': string;
}
export const cssExports: CssExports;
export default cssExports;
