// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'lady-page': string;
  'lady-page--centered': string;
  'lady-page__content': string;
  'lady-page__content--centered': string;
  'lady-page__logo': string;
}
export const cssExports: CssExports;
export default cssExports;
