// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'leaflet-control-zoom': string;
  'leaflet-tile-pane': string;
}
export const cssExports: CssExports;
export default cssExports;
