// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amplifier': string;
  'request-new-password-success__back': string;
  'request-new-password-success__button': string;
  'request-new-password-success__page': string;
  'request-new-password-success__title': string;
  'text--primary': string;
}
export const cssExports: CssExports;
export default cssExports;
