// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'request-location-toast': string;
  'request-location-toast__button': string;
  'request-location-toast__buttons': string;
}
export const cssExports: CssExports;
export default cssExports;
