name: Release - Client - Test, Build & Push to Dockerhub

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.18.2-alpine3.12

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
  
  docker:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t client .
        
      - name: Tag + Push
        run: |
          tag="release-$(date +%s)"
          docker tag client "${{ secrets.DOCKER_ORGANIZATION }}/client:$tag"
          docker tag client "${{ secrets.DOCKER_ORGANIZATION }}/client:latest"
          docker push "${{ secrets.DOCKER_ORGANIZATION }}/client:$tag"
          docker push "${{ secrets.DOCKER_ORGANIZATION }}/client:latest"
