name: Release - Client - Test, Build & Push to Dockerhub

on:
  push:
    branches:
      - release-*
  pull_request:
    branches:
      - release-*

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:12.18.2-alpine3.12

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm run test
  
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: docker build -t client .
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Tag + Push
        run: |
          tag="${{ steps.extract_branch.outputs.branch }}"
          docker tag client "${{ secrets.DOCKER_ORGANIZATION }}/client:$tag"
          docker push "${{ secrets.DOCKER_ORGANIZATION }}/client:$tag"
